In [5]:
from sklearn.decomposition import PCA
import numpy as np

# Sample data
X = np.array([[1, 2, 3], [5, 4, 3], [19, 15, 10]])

# Perform PCA and select the number of components to retain
n_components =1
pca = PCA(n_components=n_components)
X_reduced = pca.fit_transform(X)

# Inverse transform to reconstruct the original data
X_original = pca.inverse_transform(X_reduced)

print("Original data:")
print(X)
print("X_reduced data:")
print(X_reduced)
print("Reconstructed data:")
print(X_original)


Original data:
[[ 1  2  3]
 [ 5  4  3]
 [19 15 10]]
X_reduced data:
[[-9.14843881]
 [-4.97708294]
 [14.12552175]]
Reconstructed data:
[[ 1.37237036  1.84122896  2.39632661]
 [ 4.54631669  4.19344121  3.73549502]
 [19.08131296 14.96532983  9.86817837]]
