# 使用說明:

    1.) 在 Anaconda prompt 指令行輸入以下指令：
        pip install jieba 
        pip install BeautifulSoup4   
        pip install html5lib
    3.) 下載詞向量   cna.cbow.cwe_p.tar_g.512d.0.txt
       https://mega.nz/#!5LwDjZia!f77y-eWm90H3akg8mD9CqhOZ89NihirRKN4IT1SJ01Q
   


load_WordVector() {
    cna.cbow.cwe_p.tar_g.512d.0.txt
    共有158566x512
 }
>每一個字為512維
{"有關":[,,,,] ,"事件":[,,,,] ,...}

In [1]:
import numpy as np # 安裝numpy
from nlp import *

ModuleNotFoundError: No module named 'jieba'

## 載入詞向量
    1.) load_WordVector() 函式載入pre-traind word vector
    2.) set_word_vector() 傳入word vector及每個字的維度, 它會傳回word_feature()作為將字轉成512向量
    3.) word_feature()內部使用jieba進行中文分詞並使用clean_text()進行文字預處理,最後再輸出512向量

In [3]:
# 開啟詞向量檔案
dim,word_vecs=load_WordVector()
len(word_vecs['事件'])
word_feature=set_word_vector(word_vecs,dim)

158567it [00:29, 5460.14it/s]


In [3]:
len(word_feature('事件'))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\joseph\AppData\Local\Temp\jieba.cache
Loading model cost 0.607 seconds.
Prefix dict has been built successfully.


512

In [4]:
word_feature('指令')

array([ 1.262967e+00, -6.036200e-01,  3.167160e-01, -1.455487e+00,
       -1.991482e+00, -2.424292e+00, -1.311592e+00, -1.997190e-01,
        1.520551e+00, -1.048352e+00,  3.344277e+00,  1.128341e+00,
        1.574050e+00, -6.192130e-01,  6.261800e-01,  1.323959e+00,
        2.166757e+00, -4.184460e-01,  9.930450e-01, -2.626542e+00,
       -8.920940e-01,  3.568270e-01,  2.419509e+00, -2.205565e+00,
        7.157580e-01, -2.263819e+00, -2.163546e+00, -1.234982e+00,
        3.819496e+00,  1.574923e+00,  1.381490e+00, -1.920853e+00,
        1.196859e+00,  2.130985e+00, -3.173210e-01, -1.125795e+00,
       -1.654662e+00, -1.467344e+00,  1.636490e+00,  1.112630e+00,
        8.939760e-01, -3.382010e-01,  4.421630e-01, -1.232672e+00,
        1.633482e+00, -1.112951e+00,  1.057318e+00,  1.695260e+00,
        1.173000e+00, -1.228962e+00,  1.089833e+00,  3.006890e+00,
        7.588600e-01,  1.290922e+00, -1.184653e+00,  2.056010e-01,
        1.119567e+00,  1.396430e-01, -1.169152e+00,  5.555940e

In [5]:
x=[word_feature(i) for i in ['花','葉子','選民','投票','政黨','陽明山']]

In [6]:
for i in range(len(x)):
    ang=cosine_similarity(x[0],x[i])
    print(ang)

1.0000000000000002
0.17725090123061862
-0.03853492401316087
-0.12736015630429218
-0.19698887505058357
0.04873562515696748


In [7]:
for i in range(len(x)):
    ang=euclidean_distance(x[0],x[i])
    print(ang)

0.0
44.555672813660685
52.33226448196456
52.399350292173054
62.53157652422995
47.187550736048685


In [8]:
cosine_similarity

<function nlp.cosine_similarity(x, y)>

## 中文分詞
    sentence_list()函式內部利用jieba.cut 將句子作分詞, 對於有在word_vecs裡面的詞我們才把它取出,
    最後詞向量加總取平均，作為該句子的向量表示

In [4]:
dialogue = "如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!"
answers = [
  "其實狗搖尾巴有很多種方式,高興搖尾巴,生氣也搖尾巴",  
  "如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題",
  "所以只要依照政府規定,在採收前十天不要噴灑農藥", 
  "靜電才是加油站爆炸的元凶,手機不過是代罪羔羊",
  "我們可以用表面張力及附著力的原理,來測試看看",
  "不過蝦子死亡後 身體會釋放出有毒素的體液,可能造成水的變質"]


In [12]:
word_feature(answers[0])

array([-7.32000000e-02,  2.38392714e-01,  1.59864843e+00,  1.79006457e+00,
       -3.51676143e-01, -9.03601143e-01,  5.45086429e-01,  1.03452629e+00,
        2.51215614e+00,  4.84255000e-01, -2.04217571e-01, -5.79972571e-01,
       -2.22247314e+00, -5.25176143e-01,  5.17249429e-01, -2.93971429e-02,
        7.23630857e-01,  2.15680286e-01,  3.47053429e-01, -6.94137857e-01,
       -3.62268857e-01, -1.82016286e+00, -2.51094143e-01, -1.22473600e+00,
       -2.58298143e-01, -6.70032571e-01,  1.63302743e+00, -4.46973000e-01,
       -6.98531000e-01,  3.92321857e-01,  4.19644429e-01, -8.84650000e-02,
        5.30672714e-01, -1.05801086e+00,  1.92333671e+00,  4.25944286e-01,
       -6.12054714e-01, -4.15502429e-01, -3.93010000e-02, -1.48666943e+00,
       -8.42972286e-01, -1.65571286e-01, -1.79992257e+00, -1.55457514e+00,
       -2.96129571e-01, -5.06416286e-01,  1.94776714e-01, -3.46169857e-01,
       -1.71410714e-01,  2.78979286e-01, -4.64430143e-01,  7.50154286e-02,
       -8.13201143e-01,  

In [5]:
dialogue

'如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!'

In [6]:
import jieba
sg_list = jieba.cut('如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!',cut_all=False)
list(sg_list)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\joseph\AppData\Local\Temp\jieba.cache
Loading model cost 0.584 seconds.
Prefix dict has been built successfully.


['如果',
 '飛機',
 '在',
 '飛行',
 '當中',
 '打',
 '一個',
 ',',
 '小洞',
 '的',
 '話',
 '，',
 '會不會',
 '影響',
 '飛行',
 '的',
 '安全',
 '呢',
 '!']

In [8]:
dialogue

'如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!'

In [13]:
clean_text('運動房')

['運動房']

In [9]:
clean_text(dialogue)

['飛機', '飛行', '當中', '一個', '小洞', '會不會', '影響', '飛行', '安全']

In [16]:
word_feature('飛機')

array([ 4.568930e-01, -1.590691e+00,  6.746730e-01,  2.506953e+00,
       -7.930900e-01,  1.206980e-01, -2.446726e+00,  9.992290e-01,
       -1.013987e+00, -1.496220e-01,  1.729116e+00,  1.505736e+00,
       -1.228672e+00, -2.077469e+00,  2.563616e+00,  1.090978e+00,
       -1.332146e+00, -8.695200e-02, -7.016060e-01, -3.840320e-01,
        5.036970e-01,  5.830930e-01,  4.804891e+00, -7.057610e-01,
       -8.873680e-01, -7.370510e-01, -2.396450e-01, -6.004500e-01,
        9.438800e-02,  7.815500e-02,  1.502311e+00,  2.849630e-01,
       -1.413550e+00, -2.597490e+00,  1.173509e+00,  2.514140e-01,
       -3.164130e-01, -3.316681e+00,  7.291340e-01, -4.798340e-01,
        1.260665e+00, -2.329130e-01, -7.918980e-01,  1.328316e+00,
        5.251360e-01, -3.355486e+00,  1.508041e+00,  9.358240e-01,
        3.773632e+00,  1.404455e+00,  4.722370e-01,  2.236763e+00,
       -1.678901e+00, -6.812150e-01, -2.636150e-01,  5.334240e+00,
        3.003763e+00, -1.664210e+00,  2.016626e+00,  1.049414e

In [17]:
clean_text(answers[0])

['其實', '狗搖', '尾巴', '很多', '方式', '高興搖', '尾巴', '生氣', '也搖', '尾巴']

In [10]:
dialogue

'如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!'

In [18]:
avg_dlg_emb=word_feature(dialogue)

In [19]:
avg_dlg_emb

array([-3.67697875e-01, -3.11173125e-01,  2.95376500e-01,  2.24490375e-01,
       -1.57557925e+00, -1.59078750e-01, -4.75793250e-01,  1.01869500e-01,
       -8.30174875e-01, -1.06348475e+00,  5.39035125e-01,  6.39356750e-01,
       -9.19912500e-03, -9.34819625e-01,  7.21718500e-01, -4.83544875e-01,
       -2.34878500e-01,  4.21065375e-01,  2.74872000e-01, -4.27728625e-01,
        5.29375500e-01, -3.67538500e-01,  1.91623500e+00, -8.94473750e-02,
       -1.63189000e-01, -3.60846250e-01, -5.07694250e-01, -2.35777875e-01,
       -6.06292000e-01, -4.13553625e-01,  1.00936113e+00,  7.52891250e-01,
       -5.11950250e-01, -5.87243000e-01,  9.40535250e-01,  5.92872125e-01,
        3.07687500e-03, -1.42550825e+00,  8.77137750e-01, -5.85329250e-01,
        7.51469500e-01, -3.36439500e-01, -1.19102887e+00,  1.01154625e-01,
        4.57779125e-01, -1.60291300e+00,  3.31949500e-01,  1.26035750e-01,
        7.60547750e-01,  9.57895000e-01, -3.95087500e-03,  1.38711450e+00,
       -9.59979625e-01, -

In [17]:

def predict(question,answers,debug=False):
    unknown = "我不懂您在說什麼。"
    avg_dlg_emb=word_feature(question)
#     print('Question:',question)
    if (debug):
        print(clean_text(question))

    max_idx = -1
    max_sim = -10
    # 在六個回答中，每個答句都取詞向量平均作為向量表示
    # 我們選出與dialogue句子向量表示cosine similarity最高的短句
    for idx,ans in enumerate(answers):
        avg_ans_emb=word_feature(ans)
        sim = cosine_similarity(avg_dlg_emb,avg_ans_emb)

        if (debug):
            print("Ans #%d:%s:" %  (idx,clean_text(ans)))
            print("Similarity #%d: %f" % (idx, sim))
        if sim > max_sim:
            max_idx = idx
            max_sim = sim

    if max_sim < 0.3:
        return unknown
    else:
        print("Answer(%d:prob=%f):%s" % (max_idx,max_sim,answers[max_idx]))
        return answers[max_idx]

    


In [13]:
dialogue

'如果飛機在飛行當中打一個,小洞的話，會不會影響飛行的安全呢!'

In [18]:
predict(dialogue,answers,debug=False)

Answer(1:prob=0.334557):如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題


'如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題'

In [19]:
answers

['其實狗搖尾巴有很多種方式,高興搖尾巴,生氣也搖尾巴',
 '如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題',
 '所以只要依照政府規定,在採收前十天不要噴灑農藥',
 '靜電才是加油站爆炸的元凶,手機不過是代罪羔羊',
 '我們可以用表面張力及附著力的原理,來測試看看',
 '不過蝦子死亡後 身體會釋放出有毒素的體液,可能造成水的變質']

In [20]:
predict(dialogue,answers,debug=True)

['飛機', '飛行', '當中', '一個', '小洞', '會不會', '影響', '飛行', '安全']
Ans #0:['其實', '狗搖', '尾巴', '很多', '方式', '高興搖', '尾巴', '生氣', '也搖', '尾巴']:
Similarity #0: 0.180737
Ans #1:['洞', '仔細', '設計', '應該', '造成', '太大', '問題']:
Similarity #1: 0.334557
Ans #2:['政府', '規定', '採收前', '十天', '不要', '噴灑', '農藥']:
Similarity #2: 0.214191
Ans #3:['靜電才', '加油站', '爆炸', '元凶', '手機', '代罪羔羊']:
Similarity #3: 0.198871
Ans #4:['表面', '張力', '附著力', '原理', '測試', '看看']:
Similarity #4: 0.274542
Ans #5:['蝦子', '死亡', ' ', '身體', '會釋', '放出', '毒素', '體液', '可能', '造成', '水', '變質']:
Similarity #5: 0.264841
Answer(1:prob=0.334557):如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題


'如果這個洞的話經過仔細的設計的話,應該不至於造成太大問題'

## 飯店服務

In [21]:

Answer_list = [
  "在2樓使用",
  "本飯店未提供嬰兒床",
  "可到櫃台租借。費用後付",
  "無法保管貴重物品或容易損壞的行李，敬請見諒。", 
  "所有客房均可免費使用有線LAN、無線LAN來連接網路。",
  "入住為15:00以後；退房為11:00以前。",
  "您可以用信用卡付款",
  "在2樓可使用早餐",
  "飯店設有西餐廳和中式餐廳",
  "很抱歉，請避免和寵物同行住宿。但導盲犬、肢體輔助犬、導聾犬可以同行入住，如有需要，請與櫃台聯絡。",
  "客房費用請在入住時一次付清",
  "有的。健身房在飯店的10樓",
  "有的。游泳池在飯店的地下室1F",
  "有的。訂房時，請您預訂禁菸房",
  "想要像香港一樣被統的話，可以直接到對岸"]



In [22]:
Q1 = "請問入住、退房的時間？"
predict(Q1,Answer_list)

Answer(5:prob=0.836600):入住為15:00以後；退房為11:00以前。


'入住為15:00以後；退房為11:00以前。'

In [23]:
Q=["早餐在那裡使用？", 
   "可以使用信用卡嗎？",
   "請問入住、退房的時間？",
   "有禁菸房嗎？",
   "可以連接網路嗎？",
   "有嬰兒床可以借用嗎？",
   "可以和寵物一起入住嗎？",
   "飯店內有健身房嗎？",
   "飯店有游泳池嗎？",
   "飯店內有餐廳嗎？",
   "你支持一國兩制嗎?"
  ]


In [24]:
for q in Q:
    print(q)
    predict(q,Answer_list)

早餐在那裡使用？
Answer(7:prob=0.793185):在2樓可使用早餐
可以使用信用卡嗎？
Answer(6:prob=0.816887):您可以用信用卡付款
請問入住、退房的時間？
Answer(5:prob=0.836600):入住為15:00以後；退房為11:00以前。
有禁菸房嗎？
Answer(13:prob=0.621410):有的。訂房時，請您預訂禁菸房
可以連接網路嗎？
Answer(4:prob=0.691371):所有客房均可免費使用有線LAN、無線LAN來連接網路。
有嬰兒床可以借用嗎？
Answer(1:prob=0.790219):本飯店未提供嬰兒床
可以和寵物一起入住嗎？
Answer(9:prob=0.551379):很抱歉，請避免和寵物同行住宿。但導盲犬、肢體輔助犬、導聾犬可以同行入住，如有需要，請與櫃台聯絡。
飯店內有健身房嗎？
Answer(11:prob=0.907092):有的。健身房在飯店的10樓
飯店有游泳池嗎？
Answer(12:prob=0.918655):有的。游泳池在飯店的地下室1F
飯店內有餐廳嗎？
Answer(8:prob=0.833935):飯店設有西餐廳和中式餐廳
你支持一國兩制嗎?
Answer(14:prob=0.497345):想要像香港一樣被統的話，可以直接到對岸
